import type { CountryId } from "../content/types";
import {
  completeFind,
  countIndependent,
  createFindSession,
  guess,
  isValidOrder,
  nextQuestion,
  requestHint,
  type FindSession,
} from "../game/find";
import {
  createAttempt,
  isIndependentCompletion,
  markHintUsed,
  move,
  restart,
  undo,
  type TravelAttempt,
} from "../game/travel";
import type { LessonDefinition } from "../lessons/types";

export type LessonStage = "discover" | "find" | "travel" | "results";

export interface FindScore {
  independent: number;
  total: number;
}

export interface TravelResult {
  missionId: string;
  route: CountryId[];
  budget: number;
  hintUsed: boolean;
  undoUsed: boolean;
  independent: boolean;
}

/** Durable achievements. They survive "Start over" and are only ever set by gameplay. */
export interface LessonRecords {
  discoverDone: boolean;
  findDone: boolean;
  travelDone: boolean;
  lastFindScore: FindScore | null;
  bestFindScore: FindScore | null;
  travelWithoutHelp: boolean;
}

export interface LessonProgress {
  lessonId: string;
  started: boolean;
  stage: LessonStage;
  discover: { selected: CountryId | null; explored: CountryId[] };
  find: FindSession | null;
  travel: TravelAttempt | null;
  lastTravelResult: TravelResult | null;
  records: LessonRecords;
}

export type LessonAction =
  | { type: "begin" }
  | { type: "goToDiscover" }
  | { type: "discoverSelect"; country: CountryId }
  /** The order is generated by the caller (see startFindingAction) so the reducer stays pure. */
  | { type: "startFinding"; order: CountryId[] }
  | { type: "findGuess"; country: CountryId }
  | { type: "findHint" }
  | { type: "findNext" }
  /** After the last answer: on to Travel. */
  | { type: "findToTravel" }
  | { type: "travelMove"; country: CountryId }
  | { type: "travelHint" }
  | { type: "travelUndo" }
  | { type: "travelRestart" }
  | { type: "replayTravel" };

export const EMPTY_RECORDS: LessonRecords = {
  discoverDone: false,
  findDone: false,
  travelDone: false,
  lastFindScore: null,
  bestFindScore: null,
  travelWithoutHelp: false,
};

export function createLessonProgress(lesson: LessonDefinition, records: LessonRecords = EMPTY_RECORDS): LessonProgress {
  return {
    lessonId: lesson.id,
    started: false,
    stage: "discover",
    discover: { selected: null, explored: [] },
    find: null,
    travel: null,
    lastTravelResult: null,
    records,
  };
}

export function findScore(session: FindSession): FindScore {
  return { independent: countIndependent(session.results), total: session.results.length };
}

function betterScore(a: FindScore | null, b: FindScore): FindScore {
  if (!a) return b;
  return b.independent / b.total > a.independent / a.total ? b : a;
}

export function lessonReducer(lesson: LessonDefinition, state: LessonProgress, action: LessonAction): LessonProgress {
  switch (action.type) {
    case "begin":
      return { ...createLessonProgress(lesson, state.records), started: true };

    case "goToDiscover":
      return { ...state, started: true, stage: "discover" };

    case "discoverSelect": {
      if (state.stage !== "discover" || !lesson.countries.includes(action.country)) return state;
      const explored = state.discover.explored.includes(action.country)
        ? state.discover.explored
        : [...state.discover.explored, action.country];
      return { ...state, discover: { selected: action.country, explored } };
    }

    case "startFinding": {
      if (!isValidOrder(action.order, lesson.countries)) return state;
      return {
        ...state,
        started: true,
        stage: "find",
        find: createFindSession(action.order),
        records: state.stage === "discover" ? { ...state.records, discoverDone: true } : state.records,
      };
    }

    case "findGuess": {
      if (state.stage !== "find" || !state.find) return state;
      const { session } = guess(state.find, action.country, lesson.countries);
      return session === state.find ? state : { ...state, find: session };
    }

    case "findHint":
      if (state.stage !== "find" || !state.find) return state;
      return { ...state, find: requestHint(state.find) };

    case "findNext": {
      if (state.stage !== "find" || !state.find) return state;
      const session = nextQuestion(state.find);
      return session === state.find ? state : { ...state, find: session };
    }

    case "findToTravel": {
      if (state.stage !== "find" || !state.find) return state;
      const session = completeFind(state.find);
      if (session === state.find) return state;
      const score = findScore(session);
      return {
        ...state,
        find: session,
        stage: "travel",
        travel: createAttempt(lesson.borders, lesson.travel.mission),
        records: {
          ...state.records,
          findDone: true,
          lastFindScore: score,
          bestFindScore: betterScore(state.records.bestFindScore, score),
        },
      };
    }

    case "travelMove": {
      if (state.stage !== "travel" || !state.travel) return state;
      const { attempt, outcome } = move(state.travel, lesson.borders, action.country);
      if (outcome === "invalid") return state;
      if (outcome !== "arrived") return { ...state, travel: attempt };
      const independent = isIndependentCompletion(attempt);
      return {
        ...state,
        travel: attempt,
        stage: "results",
        lastTravelResult: {
          missionId: attempt.missionId,
          route: attempt.path,
          budget: attempt.budget,
          hintUsed: attempt.hintUsed,
          undoUsed: attempt.undoUsed,
          independent,
        },
        records: {
          ...state.records,
          travelDone: true,
          travelWithoutHelp: state.records.travelWithoutHelp || independent,
        },
      };
    }

    case "travelHint":
      if (state.stage !== "travel" || !state.travel) return state;
      return { ...state, travel: markHintUsed(state.travel) };

    case "travelUndo":
      if (state.stage !== "travel" || !state.travel) return state;
      return { ...state, travel: undo(state.travel) };

    case "travelRestart":
      if (state.stage !== "travel" || !state.travel) return state;
      return { ...state, travel: restart(state.travel) };

    case "replayTravel":
      if (!state.records.findDone) return state;
      return { ...state, started: true, stage: "travel", travel: createAttempt(lesson.borders, lesson.travel.mission) };
  }
}
